package cifrado_decifrado;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.security.Key;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Juanito
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        buscarArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContra = new javax.swing.JLabel();
        contrasenya = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ingreseContra = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        cifrar = new javax.swing.JButton();
        descifrar = new javax.swing.JButton();
        accion = new javax.swing.JButton();
        resultado = new java.awt.Label();
        fin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt1.setText("Cifrado y Descifrado del contenido de un fichero");

        buscarArchivo.setText("Buscar Archivo");
        buscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarArchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Presione el siguiente botón para abrir el explorador de archivos y así seleccionar el archivo ");

        txtContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContra.setText("Contraseña:");

        jLabel4.setText("¿Qué acción desea realizar?");

        cifrar.setText("Cifrar");
        cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrarActionPerformed(evt);
            }
        });

        descifrar.setText("Descifrar");
        descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descifrarActionPerformed(evt);
            }
        });

        accion.setText("Realizar acción");
        accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionActionPerformed(evt);
            }
        });

        resultado.setAlignment(java.awt.Label.CENTER);

        fin.setText("Fin");
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txt1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ingreseContra, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtContra)
                                    .addGap(18, 18, 18)
                                    .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(cifrar)
                        .addGap(113, 113, 113)
                        .addComponent(descifrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(buscarArchivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(accion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(fin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cifrar)
                            .addComponent(descifrar))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(buscarArchivo)
                .addGap(30, 30, 30)
                .addComponent(ingreseContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContra))
                .addGap(47, 47, 47)
                .addComponent(accion)
                .addGap(24, 24, 24)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(fin)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean cif = false, desci = false;
    String mensaje, direccion;
    Cifrado_Descifrado cd = new Cifrado_Descifrado();
    File f;

    private void buscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarArchivoActionPerformed
        // TODO add your handling code here:

        JFileChooser jf = new JFileChooser();
        jf.setCurrentDirectory(new File(System.getProperty("user.dir")));
        jf.showSaveDialog(null);
        direccion = jf.getSelectedFile().getAbsolutePath();
        f = new File(direccion);
        enabledAll(true);

    }//GEN-LAST:event_buscarArchivoActionPerformed

    private void cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrarActionPerformed
        // TODO add your handling code here:

        ingreseContra.setText("Ingrese una contraseña con la cual se podrá descifrar el mensaje:");
        enabledAll(true);
        visibleCifrado(false);
        cif = true;
        fin.setVisible(false);
        accion.setVisible(true);

    }//GEN-LAST:event_cifrarActionPerformed

    private void descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descifrarActionPerformed
        // TODO add your handling code here:
        ingreseContra.setText("Ingrese una contraseña para poder descifrar el mensaje:");
        enabledAll(true);
        visibleDescifrado(false);
        desci = true;
        fin.setVisible(false);
        accion.setVisible(true);

    }//GEN-LAST:event_descifrarActionPerformed

    private void accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionActionPerformed
        // TODO add your handling code here:

        FileReader fr;
        String cv = "";
        try {
            BufferedReader b = new BufferedReader(new FileReader(direccion));
            String linea;

            while ((linea = b.readLine()) != null) {
                mensaje += linea + "\n";
            }

            b.close();

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        

        if (cif == true) {

            final int LONGITUD_BLOQUE = 16;
            final String NOMBRE_FICHERO = "mensajeCifrado.txt";

            try {

                Key clave = cd.obtenerClave(contrasenya.getText(), LONGITUD_BLOQUE);
                String textoCifrado = cd.cifrar(mensaje, clave);
                PrintWriter pw = new PrintWriter(NOMBRE_FICHERO);
                pw.write(textoCifrado);
                pw.close();
                resultado.setText("El mensaje se ha cifrado correctamente");

            } catch (Exception e) {
                e.printStackTrace();

            }

            fin.setVisible(true);
            cif = false;

        } else if (desci == true) {

            final int LONGITUD_BLOQUE = 16;
            final String NOMBRE_FICHERO = "mensajeCifrado.txt";

            try {
                File file = new File(NOMBRE_FICHERO);

                Key clave = cd.obtenerClave(contrasenya.getText(), LONGITUD_BLOQUE);
                BufferedReader br = new BufferedReader(new FileReader(file));
                String textoCifrado = br.readLine();
                String mensajeDescifrado = cd.descifrar(textoCifrado, clave);
                br.close();
                resultado.setText("El mensaje se ha descifrado correctamente, este es el mensaje: " + mensajeDescifrado);
            } catch (Exception e) {
                e.printStackTrace();
            }
            desci = false;
            fin.setVisible(true);
        }
        f.delete();
    }//GEN-LAST:event_accionActionPerformed

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed
        // TODO add your handling code here:
        inicio(false);

    }//GEN-LAST:event_finActionPerformed

    private void inicio(boolean en) {

        buscarArchivo.setEnabled(en);
        contrasenya.setEditable(en);
        txtContra.setEnabled(en);
        jLabel1.setEnabled(en);
        resultado.setText("");
        contrasenya.setText("");
        accion.setVisible(en);
        descifrar.setVisible(true);
        cifrar.setVisible(true);
        ingreseContra.setText("");
    }

    private static void enabledAll(boolean en) {

        buscarArchivo.setEnabled(en);
        contrasenya.setEditable(en);
        txtContra.setEnabled(en);
        jLabel1.setEnabled(en);

    }

    private void visibleDescifrado(boolean b) {

        cifrar.setVisible(b);
        jLabel4.setVisible(b);
    }

    private void visibleCifrado(boolean b) {

        descifrar.setVisible(b);
        jLabel4.setVisible(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
                enabledAll(false);
                fin.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accion;
    private static javax.swing.JButton buscarArchivo;
    private javax.swing.JButton cifrar;
    private static javax.swing.JTextField contrasenya;
    private javax.swing.JButton descifrar;
    private static javax.swing.JButton fin;
    private java.awt.Label ingreseContra;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label resultado;
    private javax.swing.JLabel txt1;
    private static javax.swing.JLabel txtContra;
    // End of variables declaration//GEN-END:variables
}
